apiVersion: v1
kind: Secret
metadata:
  name: shubharambh-secrets
  namespace: shubharambh-production
  labels:
    app.kubernetes.io/name: shubharambh-crm
    app.kubernetes.io/component: secrets
type: Opaque
stringData:
  DATABASE_URL: "postgresql://postgres:production_password_change_me@shubharambh-postgres-svc:5432/shubharambh_db?schema=public&connection_limit=20"
  JWT_ACCESS_SECRET: "production_access_secret_super_long_change_in_prod_12345"
  JWT_REFRESH_SECRET: "production_refresh_secret_super_long_change_in_prod_67890"
  BCRYPT_SALT_ROUNDS: "12"
  REDIS_PASSWORD: ""
