apiVersion: v1
kind: Service
metadata:
  name: shubharambh-backend-svc
  namespace: shubharambh-production
  labels:
    app.kubernetes.io/name: shubharambh-crm
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
      name: http
  selector:
    app: shubharambh-backend

---
apiVersion: v1
kind: Service
metadata:
  name: shubharambh-frontend-svc
  namespace: shubharambh-production
  labels:
    app.kubernetes.io/name: shubharambh-crm
    app.kubernetes.io/component: frontend
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: shubharambh-frontend
